apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-intel-west
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  #deviceType: vfio-pci
  mtu: 9000
  nicSelector:
    deviceID: "158b"
    rootDevices:
    - "0000:86:00.0"
    vendor: "8086"
    pfNames:
    - ens7f0
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numVfs: 6
  priority: 5
  resourceName: intelnics0
