FROM centos:8
USER root
WORKDIR /root
RUN  yum -y install git @'Development Tools' which rpm-build yum-utils dnf-plugins-core \
     && yum config-manager --set-enabled PowerTools \
     && yum install -y groff libcap-ng python3 openssl-devel \
     && git clone https://github.com/openvswitch/ovs.git \
     && pushd ovs && ./boot.sh && ./configure --enable-ssl && make && make install && popd \
     && git clone https://github.com/ovn-org/ovn && pushd ovn \
     && ./boot.sh && ./configure --with-ovs-source=/root/ovs \
     && make install &&  popd
COPY start-ovs-ovn.sh /usr/local/bin
RUN chmod u+x /usr/local/bin/start-ovs-ovn.sh
WORKDIR /root
ENV PATH="${PATH}:/usr/local/share/openvswitch/scripts:/usr/local/share/ovn/scripts"
